FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["celery", "-A", "my_celery", "worker", "--loglevel=info", "-P", "eventlet"]